name: Machine Learning CI Workflow

on:
  push:
    branches:
      - main

jobs:
  ml_pipeline:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari repositori GitHub
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Setup Python versi stabil
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Install semua dependensi utama di server runner
    - name: Install Dependencies
      run: |
        pip install mlflow==2.14.1 pandas==2.2.2 scikit-learn==1.5.0

    # 4. Jalankan Re-training Model ke Cloud DagsHub via MLProject
    - name: Run MLflow Project Re-training
      working-directory: ./MLProject_Folder
      env:
        MLFLOW_TRACKING_URI: "https://dagshub.com/yehezkiel.winata06/SMSML_YEHEZKIELWINATA.mlflow"
        MLFLOW_TRACKING_USERNAME: "yehezkiel.winata06"
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        mlflow run . --env-manager local

    # 5. Login ke akun Docker Hub menggunakan GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 6. Build & Push Docker Image Secara Native (Memenuhi Syarat Mutlak Advance)
    - name: Build and Push Docker Image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: ./MLProject_Folder
        push: true
        tags: yehezkielwin/credit-card-model:latest